<?php

class Book extends Product
{

    public function __construct(
        string $title,
        int $price,
        public int $num_pages
    )
    {
       parent::__construct($title,$price);
    }

    public function info(): string
    {
        $info =  parent::info(); // TODO: Change the autogenerated stub
        return $info . "Num of pages {$this->num_pages}";

    }

}